import type { Metadata } from 'next'
import { Permanent_Marker } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Navbar'

const marker = Permanent_Marker({ subsets: ['latin'], display: 'swap', weight: '400' })

export const metadata: Metadata = {
  title: 'Photography Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={marker.className}>
            <NavBar />
            {children}
        </body>
    </html>
  )
}
